# Author: Christopher Limawan
# File: Dockerfile.development
# Purpose: Docker configuration in development container, adjusted for Tyeso web

FROM node:18-alpine
WORKDIR /app
COPY package.json ./
RUN npm install --force
COPY . .
# RUN npm run build
EXPOSE 3039
CMD ["npm", "run", "dev"]
